In [1]:
 !pip install -q pyomo

In [2]:
from pyomo.environ import *

In [3]:
import numpy as np

**Ex 2 part 1**

let $x_{ij}$ be the decision variable where \\
$x_{ij}$=1, if factory i is located at location j and 0, else. i and j $\in \{1,2,3,4,5,6,7,8,9,10,11,12 \}$.
Let $c_{ij}$ denote the setup cost of factory i at location j.\\
The required optimization problem is as follows \\
$\text{min} \sum_{i=1}^{12}\sum_{j=1}^{12}c_{ij}x_{ij}\\
  \text{s.t} \sum_{i=1}^{12}x_{ij}=1 \  \forall j\\
  \sum_{j=1}^{12}x_{ij}=1 \ \forall i\\
  x_{ij}\in\{0,1\}\ \forall\  i,j\in\{1,2,...,12\}$

In [4]:
coef=np.loadtxt('lab5_ex2.txt', delimiter=',')

In [5]:
print(coef)

[[22. 22. 19. 22. 22. 24. 18. 17. 21. 23. 19. 21.]
 [18. 12. 18. 19. 22. 21. 17. 20. 16. 17. 17. 24.]
 [19. 21. 17. 19. 17. 19. 24. 16. 18. 16. 20. 24.]
 [18. 24. 20. 21. 21. 21. 22. 19. 18. 21. 23. 23.]
 [23. 20. 19. 18. 20. 23. 22. 25. 24. 19. 21. 23.]
 [24. 16. 15. 16. 24. 21. 23. 21. 20. 20. 22. 19.]
 [22. 22. 21. 23. 18. 17. 16. 19. 24. 20. 20. 23.]
 [23. 17. 17. 17. 22. 24. 23. 20. 22. 19. 23. 21.]
 [21. 22. 21. 24. 20. 23. 19. 18. 23. 15. 25. 21.]
 [19. 19. 18. 19. 26. 24. 19. 17. 18. 20. 21. 20.]
 [20. 22. 23. 20. 22. 20. 20. 19. 17. 19. 20. 24.]
 [21. 25. 21. 19. 21. 19. 18. 16. 22. 24. 25. 24.]]


In [6]:
coef.shape

(12, 12)

In [7]:
model_lab5_ex2=ConcreteModel()

In [8]:
M=12
N=12

In [9]:
row_indices=np.arange(M)
col_indices=np.arange(N)

In [10]:
model_lab5_ex2.x=Var(col_indices,row_indices,domain=Binary)

In [11]:
#objective function is
model_lab5_ex2.objective=Objective(expr=sum(model_lab5_ex2.x[i,j]*coef[i,j] for j in col_indices for i in row_indices),sense=minimize)

In [12]:
model_lab5_ex2.constraints=ConstraintList()

In [13]:
#adding constraints to constraint list
for i in row_indices:
  model_lab5_ex2.constraints.add(sum(model_lab5_ex2.x[i,j] for j in col_indices)==1)

for j in col_indices:
  model_lab5_ex2.constraints.add(sum(model_lab5_ex2.x[i,j] for i in row_indices)==1)

In [14]:
model_lab5_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 1

In [15]:
!apt-get install -y -qq coinor-cbc

In [16]:
opt_cbc=SolverFactory('cbc')

In [17]:
result = opt_cbc.solve(model_lab5_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


**Ex 2 part 8**

In [18]:
# display solution
print('\nObjective = ', model_lab5_ex2.objective())

print('\nLocate factories in following ways')
for i in row_indices:
  for j in col_indices:
    if model_lab5_ex2.x[i,j].value==1:
      print('factory ',i+1,' will be located at location ',j+1)


Objective =  203.0

Locate factories in following ways
factory  1  will be located at location  7
factory  2  will be located at location  2
factory  3  will be located at location  5
factory  4  will be located at location  1
factory  5  will be located at location  11
factory  6  will be located at location  3
factory  7  will be located at location  6
factory  8  will be located at location  4
factory  9  will be located at location  10
factory  10  will be located at location  12
factory  11  will be located at location  9
factory  12  will be located at location  8


**Ex 2 part 9**

In [19]:
#changing domain of variables to reals
model_lab5_ex2.x.domain=Reals

In [20]:
#setting lower and upper bound
for i in row_indices:
  for j in col_indices:
    model_lab5_ex2.x[i,j].setlb(0)
    model_lab5_ex2.x[i,j].setub(1)

In [21]:
model_lab5_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 1

In [22]:
result = opt_cbc.solve(model_lab5_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [23]:
# display solution
print('\nObjective = ', model_lab5_ex2.objective())

print('\nWe will have to locate factories as follows')
for i in row_indices:
  for j in col_indices:
    if model_lab5_ex2.x[i,j].value==1:
      print('factory ',i+1,' will be located at location ',j+1,' with x[',i+1,',',j+1,']','=',model_lab5_ex2.x[i,j].value)


Objective =  203.0

We will have to locate factories as follows
factory  1  will be located at location  7  with x[ 1 , 7 ] = 1.0
factory  2  will be located at location  2  with x[ 2 , 2 ] = 1.0
factory  3  will be located at location  5  with x[ 3 , 5 ] = 1.0
factory  4  will be located at location  1  with x[ 4 , 1 ] = 1.0
factory  5  will be located at location  11  with x[ 5 , 11 ] = 1.0
factory  6  will be located at location  3  with x[ 6 , 3 ] = 1.0
factory  7  will be located at location  6  with x[ 7 , 6 ] = 1.0
factory  8  will be located at location  4  with x[ 8 , 4 ] = 1.0
factory  9  will be located at location  10  with x[ 9 , 10 ] = 1.0
factory  10  will be located at location  12  with x[ 10 , 12 ] = 1.0
factory  11  will be located at location  9  with x[ 11 , 9 ] = 1.0
factory  12  will be located at location  8  with x[ 12 , 8 ] = 1.0


**Ex 2 part 10**

Yes, the optimal cost for both problem are same and also the variables values are still integers. This is because in order to achieve optimal values the variables automaticaly achieves extreme value i.e. either 0 or 1.

**Ex 2 part 12**

We can simply add new constraints as follows \\
$x_{1,3}=0\\x_{9,5}=0\\x_{5,10}=0$

In [24]:
model_lab5_ex2.constraints.add(expr=model_lab5_ex2.x[1,3]==0)
model_lab5_ex2.constraints.add(expr=model_lab5_ex2.x[9,5]==0)
model_lab5_ex2.constraints.add(expr=model_lab5_ex2.x[5,10]==0)

In [25]:
model_lab5_ex2.x.domain=Binary

In [26]:
model_lab5_ex2.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   27 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5

In [27]:
result = opt_cbc.solve(model_lab5_ex2)
print('Solver status:', result.solver.status)
print('Solver termination condition:',result.solver.termination_condition)

Solver status: ok
Solver termination condition: optimal


In [28]:
# display solution
print('\nObjective = ', model_lab5_ex2.objective())

print('\nDecisions to be made')
for i in row_indices:
  for j in col_indices:
    if model_lab5_ex2.x[i,j].value==1:
      print('factory ',i+1,' will be located at location ',j+1)


Objective =  203.0

Decisions to be made
factory  1  will be located at location  7
factory  2  will be located at location  2
factory  3  will be located at location  5
factory  4  will be located at location  1
factory  5  will be located at location  11
factory  6  will be located at location  3
factory  7  will be located at location  6
factory  8  will be located at location  4
factory  9  will be located at location  10
factory  10  will be located at location  12
factory  11  will be located at location  9
factory  12  will be located at location  8


The optimal cost and solution is still same as in 1st problem as the newly introduced 3 constraints were already covered previously. So, they did not made any impact on the optimal solution.  